---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $REPO
  namespace: $NAMESPACE
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: $REPO
      release: $REPO
  template:
    spec:
      containers:
      - name: $REPO
        image: "$DOCKER_REGISTRY/$REPO:$NAMESPACE-$COMMIT"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
      imagePullSecrets:
        - name: ecr
---
apiVersion: v1
kind: Service
metadata:
  name: $REPO
  namespace: $NAMESPACE
spec:
  type: NodePort
  selector:
    app: $REPO
    release: $REPO
    branch: $NAMESPACE
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: $NAMESPACE-$REPO-ingress
  namespace: $NAMESPACE
spec:
  rules:
    - host: $REPO-$NAMESPACE.$DOMAIN
      http:
        paths:
          - path:
            backend:
              serviceName: $REPO
              servicePort: http
---
